export const ROLE_PROJECTION_RECEIPT_ID_PREFIX = 'role-projection:';

export const ROLE_PROJECTION_RECEIPT_ERROR = {
  MISSING: 'ROLE_PROJECTION_RECEIPT_MISSING',
  CATALOG_DRIFT: 'ROLE_PROJECTION_CATALOG_DRIFT',
  PROFILE_DRIFT: 'ROLE_PROJECTION_PROFILE_DRIFT',
  ARTIFACT_DRIFT: 'ROLE_PROJECTION_ARTIFACT_DRIFT',
} as const;
