// WORK_DEFINITION_SCHEMA_VERSION (contenido del value, validado por
// WorkDefinitionValueSchema) es DISTINTO de la columna `version` en
// packet_definitions (contador de revisiones del packet) — no confundir:
// uno versiona la FORMA del JSON, el otro versiona el CONTENIDO real.
export const WORK_DEFINITION_SCHEMA_VERSION = 1 as const;
export const WORK_DEFINITION_INITIAL_VERSION = 1;
export const WORK_DEFINITION_VERSION_INCREMENT = 1;
export const NO_WORK_DEFINITION_VERSION = 0;

export const WORK_DEFINITION_ERROR = {
  INVALID_REFERENCE: 'INVALID_WORK_DEFINITION_REFERENCE',
  UNKNOWN: 'UNKNOWN_WORK_DEFINITION',
  VERSION_NOT_FOUND: 'WORK_DEFINITION_VERSION_NOT_FOUND',
  STALE: 'STALE_WORK_DEFINITION',
  STATUS_INELIGIBLE: 'WORK_DEFINITION_STATUS_INELIGIBLE',
  INVALID_STORED_VALUE: 'INVALID_STORED_WORK_DEFINITION',
  DIGEST_MISMATCH: 'WORK_DEFINITION_DIGEST_MISMATCH',
} as const;
