import { readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const TS_EXT = '.ts';

function isFixtureFile(name: string): boolean {
  return name.startsWith('__') && name.endsWith(`__${TS_EXT}`);
}

function isCommandFile(name: string): boolean {
  return name.endsWith(TS_EXT)
    && !name.endsWith(`.test${TS_EXT}`)
    && !name.endsWith(`.constants${TS_EXT}`)
    && !name.endsWith(`.types${TS_EXT}`)
    && !name.endsWith(`.errors${TS_EXT}`)
    && !name.startsWith('index.gen')
    && !name.startsWith('generate-index')
    && !isFixtureFile(name);
}

export function scanCommandFiles(dir: string): string[] {
  const entries = readdirSync(dir, { withFileTypes: true });
  return entries
    .filter((e) => e.isFile() && isCommandFile(e.name))
    .map((e) => e.name.replace(/\.ts$/, ''))
    .sort();
}

const RESERVED = new Set([
  'break', 'case', 'catch', 'class', 'const', 'continue', 'debugger',
  'default', 'delete', 'do', 'else', 'enum', 'export', 'extends',
  'false', 'finally', 'for', 'function', 'if', 'import', 'in',
  'instanceof', 'new', 'null', 'return', 'super', 'switch', 'this',
  'throw', 'true', 'try', 'typeof', 'var', 'void', 'while', 'with',
  'implements', 'interface', 'let', 'package', 'private', 'protected',
  'public', 'static', 'yield',
]);

function safeIdent(cmd: string): string {
  return RESERVED.has(cmd) ? `${cmd}_` : cmd;
}

export function generateIndex(srcDir: string, outPath: string): void {
  const commands = scanCommandFiles(srcDir);
  const lines: string[] = [];
  lines.push('// GENERATED by generate-index.ts — do not edit');
  lines.push('// Regenerate: npx tsx src/cli/commands/generate-index.ts');
  lines.push("import type { Command } from '../command.types.js';");
  for (const cmd of commands) {
    lines.push(`import { command as ${safeIdent(cmd)} } from './${cmd}.js';`);
  }
  lines.push('');
  lines.push(`export const allCommands: readonly Command[] = [${commands.map(safeIdent).join(', ')}];`);
  lines.push('');
  writeFileSync(outPath, lines.join('\n') + '\n', 'utf8');
}

const SRC_DIR = new URL('..', import.meta.url).pathname;
const COMMANDS_DIR = join(SRC_DIR, 'commands');
generateIndex(COMMANDS_DIR, join(COMMANDS_DIR, 'index.gen.ts'));
