import { readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { COMMAND_FILE_TOKEN } from './generate-index.constants.js';

const TS_EXT = '.ts';

function isFixtureFile(name: string): boolean {
  return name.startsWith(COMMAND_FILE_TOKEN.FIXTURE_BOUNDARY)
    && name.endsWith(`${COMMAND_FILE_TOKEN.FIXTURE_BOUNDARY}${TS_EXT}`);
}

function isCommandFile(name: string): boolean {
  return name.endsWith(TS_EXT)
    && !name.endsWith(`.test${TS_EXT}`)
    && !name.endsWith(`.constants${TS_EXT}`)
    && !name.endsWith(`.types${TS_EXT}`)
    && !name.endsWith(`.errors${TS_EXT}`)
    && !name.startsWith(COMMAND_FILE_TOKEN.GENERATED_INDEX)
    && !name.startsWith(COMMAND_FILE_TOKEN.GENERATOR)
    && !isFixtureFile(name);
}

export function scanCommandFiles(dir: string): string[] {
  const entries = readdirSync(dir, { withFileTypes: true });
  return entries
    .filter((e) => e.isFile() && isCommandFile(e.name))
    .map((e) => e.name.replace(/\.ts$/, ''))
    .sort();
}

const RESERVED = new Set([
  'break', 'case', 'catch', 'class', 'const', 'continue', 'debugger',
  'default', 'delete', 'do', 'else', 'enum', 'export', 'extends',
  'false', 'finally', 'for', 'function', 'if', 'import', 'in',
  'instanceof', 'new', 'null', 'return', 'super', 'switch', 'this',
  'throw', 'true', 'try', 'typeof', 'var', 'void', 'while', 'with',
  'implements', 'interface', 'let', 'package', 'private', 'protected',
  'public', 'static', 'yield',
]);

function safeIdent(cmd: string): string {
  const identifier = cmd.replaceAll(/[^A-Za-z0-9_$]/g, '_');
  const prefixed = /^[A-Za-z_$]/.test(identifier) ? identifier : `_${identifier}`;
  return RESERVED.has(prefixed) ? `${prefixed}_` : prefixed;
}

// PRINCIPLE-009 (boilerplate generado, no autoría manual) mecanizado: el
// registry de comandos (index.gen.ts) NUNCA se edita a mano — este script
// escanea el directorio real de cli/commands/, filtra lo que no es un
// comando propiamente dicho (tests, constants, types, fixtures, el propio
// generador), y genera los imports + el array `allCommands`. Corre como
// script standalone (la línea final se auto-invoca al importar el módulo)
// vía `npx tsx generate-index.ts`, normalmente disparado por un hook/verify,
// no manualmente en el flujo normal de agregar un comando.
export function generateIndex(srcDir: string, outPath: string): void {
  const commands = scanCommandFiles(srcDir);
  const lines: string[] = [];
  lines.push('// GENERATED by generate-index.ts — do not edit');
  lines.push('// Regenerate: npx tsx src/cli/commands/generate-index.ts');
  lines.push("import type { Command } from '../command.types.js';");
  for (const cmd of commands) {
    lines.push(`import { command as ${safeIdent(cmd)} } from './${cmd}.js';`);
  }
  lines.push('');
  lines.push(`export const allCommands: readonly Command[] = [${commands.map(safeIdent).join(', ')}];`);
  lines.push('');
  writeFileSync(outPath, lines.join('\n') + '\n', 'utf8');
}

const COMMANDS_DIR = fileURLToPath(new URL('.', import.meta.url));
generateIndex(COMMANDS_DIR, join(COMMANDS_DIR, 'index.gen.ts'));
