// GENERATED by generate-index.ts — do not edit
// Regenerate: npx tsx src/cli/commands/generate-index.ts
import type { Command } from '../command.types.js';
import { command as adopt } from './adopt.js';
import { command as backup } from './backup.js';
import { command as check } from './check.js';
import { command as constitution } from './constitution.js';
import { command as describe } from './describe.js';
import { command as doctor } from './doctor.js';
import { command as docs } from './docs.js';
import { command as handoff } from './handoff.js';
import { command as import_ } from './import.js';
import { command as instructions } from './instructions.js';
import { command as rebuild } from './rebuild.js';
import { command as reconcile } from './reconcile.js';
import { command as restore } from './restore.js';
import { command as review } from './review.js';
import { command as serve } from './serve.js';
import { command as sprint } from './sprint.js';
import { command as status } from './status.js';
import { command as task } from './task.js';

export const allCommands: readonly Command[] = [adopt, backup, check, constitution, describe, doctor, docs, handoff, import_, instructions, rebuild, reconcile, restore, review, serve, sprint, status, task];
