// GENERATED by generate-index.ts — do not edit
// Regenerate: npx tsx src/cli/commands/generate-index.ts
import type { Command } from '../command.types.js';
import { command as adopt } from './adopt.js';
import { command as backup } from './backup.js';
import { command as check } from './check.js';
import { command as constitution } from './constitution.js';
import { command as context } from './context.js';
import { command as contract } from './contract.js';
import { command as daemon } from './daemon.js';
import { command as decision } from './decision.js';
import { command as describe } from './describe.js';
import { command as dispatch } from './dispatch.js';
import { command as docs } from './docs.js';
import { command as doctor } from './doctor.js';
import { command as enforce } from './enforce.js';
import { command as execution_profile } from './execution-profile.js';
import { command as handoff } from './handoff.js';
import { command as import_ } from './import.js';
import { command as instructions } from './instructions.js';
import { command as promotion } from './promotion.js';
import { command as rebuild } from './rebuild.js';
import { command as reconcile } from './reconcile.js';
import { command as restore } from './restore.js';
import { command as review } from './review.js';
import { command as role } from './role.js';
import { command as serve } from './serve.js';
import { command as sprint } from './sprint.js';
import { command as status } from './status.js';
import { command as task } from './task.js';
import { command as workflow_policy } from './workflow-policy.js';
import { command as workspace } from './workspace.js';

export const allCommands: readonly Command[] = [adopt, backup, check, constitution, context, contract, daemon, decision, describe, dispatch, docs, doctor, enforce, execution_profile, handoff, import_, instructions, promotion, rebuild, reconcile, restore, review, role, serve, sprint, status, task, workflow_policy, workspace];

