import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { randomUUID } from 'node:crypto';
import type { Store } from '../db/store.types.js';
import { stringColumn, numberColumn } from '../db/rows.js';

interface SectionRow {
  body: string;
}

interface PrincipleRow {
  id: string;
  rule: string;
  rationale: string;
  sort_order: number;
}

export function setSection(store: Store, section: string, body: string): void {
  const now = new Date().toISOString();
  const existing = getSection(store, section);
  if (existing !== null) {
    store.db
      .prepare('UPDATE constitution_sections SET body = ?, updated_at = ? WHERE section = ?')
      .run(body, now, section);
  } else {
    store.db
      .prepare('INSERT INTO constitution_sections (section, body, created_at, updated_at) VALUES (?, ?, ?, ?)')
      .run(section, body, now, now);
  }
}

export function getSection(store: Store, section: string): SectionRow | null {
  const row = store.db
    .prepare('SELECT body FROM constitution_sections WHERE section = ?')
    .get(section);
  if (row === undefined) return null;
  return { body: stringColumn(row, 'body') };
}

export function listSections(store: Store): string[] {
  return store.db
    .prepare('SELECT section FROM constitution_sections ORDER BY section')
    .all()
    .map((row) => stringColumn(row, 'section'));
}

export function listPrinciples(store: Store): PrincipleRow[] {
  return store.db
    .prepare('SELECT id, rule, rationale, sort_order FROM constitution_principles ORDER BY sort_order')
    .all()
    .map((row) => ({
      id: stringColumn(row, 'id'),
      rule: stringColumn(row, 'rule'),
      rationale: stringColumn(row, 'rationale'),
      sort_order: numberColumn(row, 'sort_order'),
    }));
}

export function addPrinciple(store: Store, rule: string, rationale: string): PrincipleRow {
  const maxOrder = store.db
    .prepare('SELECT COALESCE(MAX(sort_order), -1) AS m FROM constitution_principles')
    .get();
  const sortOrder = numberColumn(maxOrder, 'm') + 1;
  const id = randomUUID();
  store.db
    .prepare('INSERT INTO constitution_principles (id, rule, rationale, sort_order) VALUES (?, ?, ?, ?)')
    .run(id, rule, rationale, sortOrder);
  return { id, rule, rationale, sort_order: sortOrder };
}

const GENERATED_BANNER = '<!-- GENERATED by sv-playbook constitution set — do not edit by hand -->\n';

// La DB es la fuente de verdad de la constitución (visión/producto/
// principios de la instancia); esto sólo proyecta una copia legible en
// docs/constitution/ para humanos que prefieren leer markdown en el repo —
// editar ese .md directamente no tiene efecto, la próxima regeneración lo
// pisa (PRINCIPLE-012: el CLI es la única interfaz de escritura).
export function regenerateExport(repoRoot: string, section: string, body: string): void {
  const dir = join(repoRoot, 'docs', 'constitution');
  mkdirSync(dir, { recursive: true });
  const content = `${GENERATED_BANNER}\n${body}\n`;
  writeFileSync(join(dir, `${section}.md`), content, 'utf8');
}
